cc_binary(
    name="imu_app",
    srcs=["imu.cc"],
    deps=["//src/flight/devices/lsm6dsv16x:lsm6dsv16x"],
)

cc_binary(
    name="humidity_app",
    srcs=["humidity.cc"],
    deps=["//src/flight/devices/bme280:bme280"],
)