cc_library(
    name="lsm6dsv16x",
    hdrs=["lsm6dsv16x.hpp"],
    srcs=["lsm6dsv16x.cc"],
    visibility=["//visibility:public"],
    deps=["@rpi_hw_cc//:rpi_hw", "@lsm6dsv16x_regs_cc//:lsm6dsv16x_regs"]
)